// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: pkg/proto/notification.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	SendSMSNotification(ctx context.Context, in *SendSMSNotificationRequest, opts ...grpc.CallOption) (*SendSMSNotificationResponse, error)
	SendSlackNotification(ctx context.Context, in *SendSlackNotificationRequest, opts ...grpc.CallOption) (*SendSlackNotificationResponse, error)
	SendMailNotification(ctx context.Context, in *SendMailNotificationRequest, opts ...grpc.CallOption) (*SendMailNotificationResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SendSMSNotification(ctx context.Context, in *SendSMSNotificationRequest, opts ...grpc.CallOption) (*SendSMSNotificationResponse, error) {
	out := new(SendSMSNotificationResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/SendSMSNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendSlackNotification(ctx context.Context, in *SendSlackNotificationRequest, opts ...grpc.CallOption) (*SendSlackNotificationResponse, error) {
	out := new(SendSlackNotificationResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/SendSlackNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendMailNotification(ctx context.Context, in *SendMailNotificationRequest, opts ...grpc.CallOption) (*SendMailNotificationResponse, error) {
	out := new(SendMailNotificationResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/SendMailNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	SendSMSNotification(context.Context, *SendSMSNotificationRequest) (*SendSMSNotificationResponse, error)
	SendSlackNotification(context.Context, *SendSlackNotificationRequest) (*SendSlackNotificationResponse, error)
	SendMailNotification(context.Context, *SendMailNotificationRequest) (*SendMailNotificationResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) SendSMSNotification(context.Context, *SendSMSNotificationRequest) (*SendSMSNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSMSNotification not implemented")
}
func (UnimplementedNotificationServiceServer) SendSlackNotification(context.Context, *SendSlackNotificationRequest) (*SendSlackNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSlackNotification not implemented")
}
func (UnimplementedNotificationServiceServer) SendMailNotification(context.Context, *SendMailNotificationRequest) (*SendMailNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMailNotification not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_SendSMSNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSMSNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendSMSNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/SendSMSNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendSMSNotification(ctx, req.(*SendSMSNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendSlackNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSlackNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendSlackNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/SendSlackNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendSlackNotification(ctx, req.(*SendSlackNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendMailNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMailNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendMailNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/SendMailNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendMailNotification(ctx, req.(*SendMailNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSMSNotification",
			Handler:    _NotificationService_SendSMSNotification_Handler,
		},
		{
			MethodName: "SendSlackNotification",
			Handler:    _NotificationService_SendSlackNotification_Handler,
		},
		{
			MethodName: "SendMailNotification",
			Handler:    _NotificationService_SendMailNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/notification.proto",
}
