version: "3.5"

services:
  server-dev:
    build:
      target: dev
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${GOPATH}/pkg/mod:/go/pkg/mod:cached
      - ${GOCACHE}:/cache/go:cached
      - .:/go/src/github.com/kkereziev/notifier:cached
    ports:
      - "8001:8000"
    env_file:
      - .env
    command:
      - "CompileDaemon"
      - "-log-prefix=false"
      - "-graceful-kill=true"
      - "-build=go build -o ./build/server main.go"
      - "-command=./build/server"

  server:
    build:
      target: prod
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
